<a href="https://colab.research.google.com/github/Ru1chi/NLP/blob/main/Word2Vec.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import os

# Create a new folder named 'my_folder'
os.makedirs('my_folder', exist_ok=True)

# Verify the folder was created
os.listdir()


['.config', 'my_folder', 'sample_data']

In [4]:
import pandas as pd
import numpy as np

In [6]:
import gensim
import os

In [10]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [11]:
story=[]


In [13]:
for filename in os.listdir('my_folder'):
    # Open the file with the correct encoding
    with open(os.path.join('my_folder',filename), encoding='windows-1252') as f:
        corpus=f.read()
    raw_sent=sent_tokenize(corpus)#converting the string into sentenced tokens
    for sent in raw_sent:
        story.append(simple_preprocess(sent))

In [14]:
len(story)

174912

In [17]:
story[:10]

[['clash',
  'of',
  'kings',
  'book',
  'two',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'the',
  'comet',
  'tail',
  'spread',
  'across',
  'the',
  'dawn',
  'red',
  'slash',
  'that',
  'bled',
  'above',
  'the',
  'crags',
  'of',
  'dragonstone',
  'like',
  'wound',
  'in',
  'the',
  'pink',
  'and',
  'purple',
  'sky'],
 ['the',
  'maester',
  'stood',
  'on',
  'the',
  'windswept',
  'balcony',
  'outside',
  'his',
  'chambers'],
 ['it', 'was', 'here', 'the', 'ravens', 'came', 'after', 'long', 'flight'],
 ['their',
  'droppings',
  'speckled',
  'the',
  'gargoyles',
  'that',
  'rose',
  'twelve',
  'feet',
  'tall',
  'on',
  'either',
  'side',
  'of',
  'him',
  'hellhound',
  'and',
  'wyvern',
  'two',
  'of',
  'the',
  'thousand',
  'that',
  'brooded',
  'over',
  'the',
  'walls',
  'of',
  'the',
  'ancient',
  'fortress'],
 ['when',
  'first',
  'he',
  'came',
  'to',
  'dragonstone',
  'the',
  

In [19]:
model=gensim.models.Word2Vec(
    window=10,
    min_count=2,
    workers=4,
    vector_size=100
)

In [20]:
model.build_vocab(story)

In [23]:
model.train(story,total_examples=model.corpus_count,epochs=model.epochs)

(7780318, 10199830)

In [25]:
model.wv.most_similar('daenerys')

[('stormborn', 0.808797299861908),
 ('targaryen', 0.7963671684265137),
 ('unburnt', 0.725300669670105),
 ('dorne', 0.6994339227676392),
 ('queen', 0.6936737298965454),
 ('myrcella', 0.6799183487892151),
 ('elia', 0.6746637225151062),
 ('princess', 0.6726328134536743),
 ('martell', 0.6664652228355408),
 ('blessed', 0.6433727145195007)]

In [27]:
model.wv.doesnt_match(['jon','rikon','robb','arya','sansa','bran'])

'jon'

In [28]:
model.wv['king']

array([ 2.9207542e+00,  1.8571668e+00,  3.5955346e-01,  2.3405976e+00,
       -2.3327520e+00,  1.0341238e+00,  1.2468548e+00, -1.5049655e+00,
       -2.4156563e+00, -1.3061492e+00,  5.7266452e-03, -1.4465235e+00,
        1.3741157e+00,  1.0356839e+00,  1.6055170e-01,  1.9993889e-01,
        3.6079937e-01,  1.9373821e+00,  2.6225957e-01,  1.0543743e+00,
        2.3478372e+00, -1.7130735e+00,  2.6858525e+00,  5.7012558e-02,
       -1.2675807e+00,  1.0734637e+00, -8.2912099e-01, -6.5948021e-01,
       -1.9586033e+00,  3.2412798e+00, -2.3782108e+00,  2.3407557e+00,
        1.8494362e-01, -6.2312663e-02,  1.8307728e+00, -2.7711792e+00,
       -2.1659801e+00, -1.6090524e+00,  5.6727111e-01,  2.3359701e-01,
       -4.5729953e-01,  1.0895026e+00,  4.0758696e+00,  2.0251815e+00,
       -1.2106923e+00, -1.3031598e+00,  1.4916002e+00, -1.0816287e+00,
        3.0709107e+00, -9.6194822e-01, -4.3590951e+00, -1.5442795e+00,
        1.0005289e+00, -2.8893080e+00,  3.3886964e+00, -3.7568617e+00,
      

In [29]:
model.wv['king'].shape

(100,)

In [30]:
model.wv.similarity('arya','sansa')

0.80608475

In [31]:
model.wv.similarity('cersei','sansa')

0.72955835

In [32]:
model.wv.similarity('tywin','sansa')

0.21944539

In [33]:
model.wv.get_normed_vectors()

array([[-0.05247006, -0.01043416,  0.10308905, ..., -0.00730846,
        -0.09423282,  0.02694651],
       [-0.09621334,  0.07133703,  0.07555152, ...,  0.0459105 ,
        -0.07227165,  0.04810634],
       [ 0.07451425, -0.10524847, -0.01570857, ..., -0.02366609,
         0.19183831, -0.15507992],
       ...,
       [-0.129485  , -0.08141056, -0.13849735, ..., -0.10143756,
         0.08147921,  0.05409241],
       [-0.12904173,  0.12691733, -0.0254255 , ..., -0.2634407 ,
        -0.07652014, -0.0101083 ],
       [-0.1478736 ,  0.0987364 ,  0.09373046, ..., -0.22023597,
         0.02376457,  0.01547715]], dtype=float32)

In [34]:
model.wv.get_normed_vectors().shape

(18635, 100)

In [35]:
y=model.wv.index_to_key

In [36]:
y

['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'on',
 'at',
 'my',
 'said',
 'have',
 'be',
 'lord',
 'them',
 'no',
 'from',
 'me',
 'would',
 'were',
 'your',
 'one',
 'when',
 'all',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'could',
 'we',
 'are',
 'man',
 'there',
 'this',
 'up',
 'what',
 'been',
 'did',
 'by',
 'king',
 'do',
 'men',
 'out',
 'back',
 'more',
 'or',
 'who',
 'well',
 'down',
 'than',
 'only',
 'like',
 'jon',
 'tyrion',
 'father',
 'some',
 'hand',
 'old',
 'even',
 'never',
 'see',
 'off',
 'before',
 'too',
 'an',
 'into',
 'know',
 'now',
 'made',
 'black',
 'told',
 'eyes',
 'thought',
 'lady',
 'time',
 'how',
 'long',
 'then',
 'come',
 'has',
 'can',
 'where',
 'page',
 'us',
 'll',
 'through',
 'might',
 'here',
 'face',
 'still',
 'way',
 'red',
 'head',
 'boy',
 'must',
 'brother',
 'once',
 'over',
 'good',
 'two',
 'night',
 '

In [37]:
from sklearn.decomposition import PCA

In [38]:
pca=PCA(n_components=3)

In [40]:
X=pca.fit_transform(model.wv.get_normed_vectors())

In [41]:
X[:5]

array([[-0.11701339,  0.5603192 , -0.06119316],
       [-0.15382785,  0.33877635,  0.04330125],
       [ 0.2976179 ,  0.5348628 ,  0.16768959],
       [ 0.03409097,  0.330864  , -0.12566273],
       [ 0.12735566,  0.5141895 ,  0.22072   ]], dtype=float32)

In [42]:
import plotly.express as px

In [44]:
fig=px.scatter_3d(X[200:300],x=0,y=1,z=2,color=y[200:300])
fig.show()